apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx  # Make sure you're using the correct namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - name: nginx-ingress-controller
        image: nginx/nginx-ingress-controller:latest  # Ensure the image version is correct
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
          - "/nginx-ingress-controller"
          - "--configmap=ingress-nginx/nginx-ingress-controller"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  selector:
    app: nginx-ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer  # You can use NodePort if LoadBalancer is unavailable
