name: SRE Assignment CI Workflow

on:
  push:
    branches:
      - main
      - develop
      - preprod
  pull_request:
    branches:
      - main
      - develop
      - preprod

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install hey for load testing
    - name: Install hey
      run: |
        curl -L -o hey https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64
        chmod +x hey
        sudo mv hey /usr/local/bin/

    # Set up KinD (Kubernetes in Docker)
    - name: Set up KinD
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind create cluster --config=k8s/cluster-config.yaml

    # Deploy NGINX Ingress Controller
    - name: Deploy NGINX Ingress Controller
      run: kubectl apply -f k8s/ingress-controller.yaml

    # Deploy foo and bar services
    - name: Deploy foo and bar
      run: |
        kubectl apply -f k8s/foo-deployment.yaml
        kubectl apply -f k8s/bar-deployment.yaml

    # Deploy Prometheus and Grafana
    - name: Deploy Prometheus and Grafana
      run: |
        kubectl apply -f k8s/prometheus-deployment.yaml
        kubectl apply -f k8s/grafana-deployment.yaml

    # Run Load Test
    - name: Run Load Test
      run: bash scripts/load-test.sh

    # Post Load Test Result as PR Comment
    - name: Post Load Test Result as PR Comment
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat load-test-result.txt)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
